name: Windows Qt Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt (MSVC)
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.10.1'
          arch: 'win64_msvc2022_64'

      - name: Configure (MSVC)
        run: >
          cmake -S . -B build
          -G "Visual Studio 17 2022"
          -A x64
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_PREFIX_PATH="${{ env.Qt6_DIR }}"

      - name: Build
        run: cmake --build build --config Release

      - name: Deploy Qt runtime
        run: |
          mkdir deploy
          copy build\Release\searchalgos.exe deploy\


          # Copy map & scenario files
          copy Boston_0_512.map deploy\
          copy Boston_0_512.map.scen deploy\
          
          & "$env:QT_ROOT_DIR\bin\windeployqt.exe" deploy\searchalgos.exe

      - name: Package
        run: |
          set VERSION=${{ github.ref_name }}
          if (-not $version) { $version = "dev" }
          powershell Compress-Archive deploy searchalgos-windows-$version.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          files: |
            README.md
            LICENSE_Qt-LGPL.txt
            Boston_0_512.map
            Boston_0_512.map.scen


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: searchalgos-windows
          path: searchalgos-windows-*.zip
