name: Windows Qt Build

on:
  push:
    branches: [ main, release_stuff ]
    tags:
      - 'v*'
  pull_request:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Qt
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.10.1'
          arch: 'win64_msvc2022_64'
          modules: 'qtbase'

      - name: Configure
        run: |
          cmake -S . -B build -G "Ninja" ^
                -DCMAKE_BUILD_TYPE=Release ^
                -DCMAKE_PREFIX_PATH="${{ env.Qt6_DIR }}"

      - name: Build
        run: |
          cmake --build build --config Release

      - name: Deploy Qt runtime
        run: |
          mkdir deploy
          copy build\yourapp.exe deploy\
          windeployqt deploy\searchalgos.exe

      - name: Package
        run: |
          $version = ${{ github.ref_name || 'pre1.0' }}
          powershell Compress-Archive deploy searchalgos-windows-$version.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: searchalgos-windows
          path: searchalgos-windows.zip
